import "./globals.css";

export const metadata = {
  title: "WebDev 2 Demos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body>{children}</body> {/* /*Children will represent every page*/}
    </html>
  );
}
